CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL,
  is_admin VARCHAR(1) NOT NULL DEFAULT '0',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE perguntas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_1 VARCHAR(255) NOT NULL,
  item_2 VARCHAR(255) NOT NULL,
  item_3 VARCHAR(255) NOT NULL,
  item_4 VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE exames (
  id INT AUTO_INCREMENT PRIMARY KEY,
  link VARCHAR(255) NOT NULL,
  estado VARCHAR(255) NOT NULL,
  userId INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE respostas (
  userId INT NOT NULL,
  perguntaId INT NOT NULL,
  resposta_1 VARCHAR(255) NOT NULL,
  resposta_2 VARCHAR(255) NOT NULL,
  resposta_3 VARCHAR(255) NOT NULL,
  resposta_4 VARCHAR(255) NOT NULL,
  tempo_a_responder VARCHAR(255) NOT NULL,
  estado VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE respostas ADD UNIQUE (userId, perguntaId);